export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const ERROR_LOG = "ERROR_LOG";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGN_OFF = "SIGN_OFF";

export const NOTIFICATIONS = "NOTIFICATIONS";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const VALIDATE_NOTIFICATION = "VALIDATE_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const STATE_NOTIFICATION = "STATE_NOTIFICATION";
export const CURRENT_NOTIFICATION = "CURRENT_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const CURRENT_CLEAN = "CURRENT_CLEAN";
export const CLEAN = "CLEAN";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
